---
- name: Setup docker
  include_role:
    name: docker_tools

#- name: Copy grafana configs
#  copy:
#    src: "{{ item }}"
#    dest: /opt/
#  with_items:
#    - 'dash'
#    - 'provisioning'
#
#- name: Copy grafana configs
#  template:
#    src: "{{ item }}"
#    dest: /opt/grafana.ini
#  with_items:
#    - 'grafana.ini.j2'

- name: Run Grafana container
  register: grafana_container
  docker_container:
      name: grafana
      image: grafana/grafana
      network_mode: host
      restart_policy: always
      ports: "3000:3000"
      restart: yes
      volumes:
        #- "/opt/grafana.ini:/etc/grafana/grafana.ini"
        #- "/opt/provisioning:/etc/grafana/provisioning" 
        #- "/opt/dash:/var/lib/grafana/dashboards"

- name: Add proxy config
  include_tasks: nginx_conf.yaml
  when:
  - proxied|bool == true