---
  all:
    children: 
      monitoring:
        hosts:
          grafana:
            ansible_host: 18.185.59.17
            roles:
              - nginx
              - docker_tools
              - grafana
              - letsencrypt
              - node-exporter
              - prometheus
            ansible_ssh_private_key_file: ~/.ssh/key.pem
            ansible_user: ubuntu
            ansible_port: 22      
    vars:
      ansible_become: yes
      ansible_become_method: sudo