############## Hendlers ##############
- name: start node_exporter 
  service: 
    name: node_exporter 
    state: started

- name: restart node_exporter 
  service: 
    name: node_exporter 
    state: restarted
